# --- SUBSTITUTION VARIABLES ---
substitutions:
  _REGION: europe-west1
  _PROJECT_ID: auth-demo-479410
  _IMAGE_PATH: europe-west1-docker.pkg.dev/${_PROJECT_ID}/quota-repo/backend:$COMMIT_SHA
  _SERVICE_ACCOUNT_EMAIL: 40515463332-compute@developer.gserviceaccount.com
  _SQL_INSTANCE: ${_PROJECT_ID}:${_REGION}:django-db

steps:
# 1. Build the Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: Build-Image
  args:
    - 'build'
    - '-t'
    - '${_IMAGE_PATH}'
    - '.'

# 2. Push the Image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push-Image
  args: ['push', '${_IMAGE_PATH}']

# 3. Run Database Migrations (Critical Pre-Deployment Step)
# This step executes a Cloud Run Job. This job will run 'python manage.py migrate'
# and exit, ensuring the DB is updated before the web service starts.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Run-Migrations
  entrypoint: gcloud
  args:
  - run
  - jobs
  - execute
  - django-migrate-job # Name of the Cloud Run Job template (must be created once manually)
  - --region
  - ${_REGION}
  - --image
  - ${_IMAGE_PATH}
  - --wait # Wait for the migration job to complete before moving to deployment
  - --command # The actual Python command from your container
  - python manage.py migrate
  - --args
  - "--noinput"
  - --service-account=${_SERVICE_ACCOUNT_EMAIL}
  - --set-cloudsql-instances=${_SQL_INSTANCE}
  # Pass DB connection details via env vars and secrets
  - --set-env-vars=DB_USER=django-user,DB_NAME=django-db,DB_HOST=/cloudsql/${_SQL_INSTANCE}
  - --set-secrets=DB_PASSWORD=django-db-secret:latest

# 4. Deploy the New Service Revision to Cloud Run
# Updates the main service with the new image and configurations.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy-Service
  entrypoint: gcloud
  args:
  - run
  - deploy
  - django-backend-service
  - --region
  - ${_REGION}
  - --image
  - ${_IMAGE_PATH}
  - --platform
  - managed
  - --allow-unauthenticated # Allows public access for your Next.js frontend
  - --min-instances=0 # ESSENTIAL for cost-saving (scales down to zero)
  - --service-account=${_SERVICE_ACCOUNT_EMAIL}
  - --set-cloudsql-instances=${_SQL_INSTANCE}
  - --update-secrets=DB_PASSWORD=django-db-secret:latest
  - --update-env-vars=DB_USER=django-user,DB_NAME=django-db,DB_HOST=/cloudsql/${_SQL_INSTANCE}